apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb-headless
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongodb/mongodb-community-server
          imagePullPolicy: IfNotPresent
          command:
            - "mongod"
            - "--bind_ip_all"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_REPLICA_SET_MODE
              value: "replicaset"
            - name: MONGO_REPLICA_SET_NAME
              value: "rs0"
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-username
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
            - name: MONGO_REPLICA_SET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-replica-key
          volumeMounts:
            - name: mongodb-data
              mountPath: /init/db
            - name: mongodb-init
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: 1Gi
              cpu: 500m
            limits:
              memory: 2Gi
              cpu: 1000m
      volumes:
        - name: mongodb-init
          configMap:
            name: mongodb-init
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
