apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-username: ZGdkdHNyb290 # dgdtsroot
  mongodb-root-password: czZSaTdFUFA2NmpJdk9MQ0Zocmg= # s6Ri7EPP66jIvOLCFhrh
  mongodb-replica-key: RnpsblEzdDE5a0E3SDM1RmlyVFY= # FzlnQ3t19kA7H35FirTV
