apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  replica-set-mode: |
    #!/bin/sh
    if [ "${POD_NAME}" = "mongodb-0" ]; then
      echo "primary"
    else
      echo "secondary"
    fi